[project]
name = "mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "kedro>=1.0.0",
    "mangum>=0.19.0",
    "uvicorn>=0.34.2",
]
