services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8081:8000"
    volumes:
      - type: bind
        source: ./backend/data
        target: /app/data

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8000"
